build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
  i386: "ghcr.io/home-assistant/i386-base:3.15"
labels:
  org.opencontainers.image.title: "Example Golang Addon"
  org.opencontainers.image.description: "Example Addon Containerised Addon for Home Assistant"
  org.opencontainers.image.source: "https://github.com/crossowl/homeassistant-addons/tree/main/co-go-example"
  org.opencontainers.image.authors: "Chris Howell (Cross Owl)"
  org.opencontainers.image.documentation: "https://github.com/crossowl/homeassistant-addons/tree/main/co-go-example/DOCS.md"
  org.opencontainers.image.licenses: "Apache License 2.0"
args: {}

